version: '4.0'

services:
  app:
    image: gulden
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./styles:/app/styles
      - ./models:/app/models
      - ./types:/app/types
    depends_on:
      - db
  db:
    image: mongo:6.0.1-focal
    ports:
      - 27017:27017
    volumes:
      - gulden-db:/data/db
volumes:
  gulden-db: {}
